[package]
name = "nameback"
version = "0.1.0"
edition = "2021"
authors = ["Albert Hui"]
description = "Rename files based on their metadata - automatically extracts titles, dates, and descriptions"
license = "MIT"
repository = "https://github.com/h4x0r/nameback"
homepage = "https://github.com/h4x0r/nameback"
readme = "README.md"
keywords = ["metadata", "rename", "exif", "files", "utility"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
regex = "1.10"
log = "0.4"
env_logger = "0.11"
