name: Renovate
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/renovate.yml'
      - 'renovate.json'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@696f57d7c1b47aa1097f46915e93ed0bdd25d641 # v40.3.12
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
